services:
  annonariapp:
    container_name: annonariapp
    image: annonariapp:1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always
    volumes:
      - ./backend:/app 
    env_file:
      - ./backend/.env 
    command: python run.py 
  annonaria-frontend:
    container_name: annonaria-frontend
    image: annonaria-frontend:1.0.0
    build:
      context: ./frontend/annonaria-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - annonariapp
